# Generated by Django 4.0.5 on 2022-06-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP')),
                ('description', models.TextField(default='no_description', max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_info', models.TextField(default='noname', max_length=500, verbose_name='host_info')),
                ('disk_info', models.TextField(default='noname', max_length=500, verbose_name='host_info')),
                ('memory_info', models.TextField(default='noname', max_length=500, verbose_name='host_info')),
                ('cpu_info', models.TextField(default='noname', max_length=500, verbose_name='host_info')),
                ('load_avg', models.TextField(default='noname', max_length=500, verbose_name='host_info')),
            ],
            options={
                'verbose_name': 'Metrics',
                'managed': True,
            },
        ),
    ]
