# Generated by Django 4.0.5 on 2022-06-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='cpu_info',
            field=models.TextField(default='noname', max_length=1000, verbose_name='host_info'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='disk_info',
            field=models.TextField(default='noname', max_length=1000, verbose_name='host_info'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='host_info',
            field=models.TextField(default='noname', max_length=1000, verbose_name='host_info'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='load_avg',
            field=models.TextField(default='noname', max_length=1000, verbose_name='host_info'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='memory_info',
            field=models.TextField(default='noname', max_length=1000, verbose_name='host_info'),
        ),
    ]
